# Generated by Django 6.0.3 on 2026-04-05 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор вопроса', primary_key=True, serialize=False)),
                ('question_title', models.CharField(help_text='Краткое описание вопроса', max_length=300)),
                ('question_body', models.TextField(help_text='Тело вопроса (сам текст)')),
                ('question_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('solved', 'Solved')], default='open', help_text='Статус вопроса', max_length=20)),
                ('question_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания вопроса')),
                ('question_updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения вопроса')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор решения', primary_key=True, serialize=False)),
                ('solution_body', models.TextField(help_text='Тело решения (сам текст)')),
                ('solution_is_best', models.BooleanField(default=False, help_text='Является ли решение лучшим')),
                ('solution_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания решения')),
                ('solution_updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения решения')),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
        migrations.CreateModel(
            name='SolutionEdits',
            fields=[
                ('solution_edit_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор изменения', primary_key=True, serialize=False)),
                ('solution_edit_body_before', models.TextField(help_text='Текст решения до правок')),
                ('solution_edit_body_after', models.TextField(help_text='Новый текст решения')),
                ('solution_edit_is_approved', models.BooleanField(blank=True, help_text='Была ли одобрена правка', null=True)),
                ('solution_edit_edited_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время правки')),
            ],
            options={
                'db_table': 'solution_edits',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор голоса', primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID объекта, к которому поставлен голос')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], help_text='Тип голоса (upvote или downvote)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания голоса')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения голоса')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор комментария', primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID объекта, к которому оставлен комментарий')),
                ('body', models.TextField(help_text='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания комментария')),
                ('content_type', models.ForeignKey(help_text='Тип контента (вопрос или решение)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский комментарий (для вложенных комментариев)', null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.comment')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
