# Generated by Django 6.0.3 on 2026-03-29 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор вопроса', primary_key=True, serialize=False)),
                ('question_title', models.CharField(help_text='Краткое описание вопроса', max_length=300)),
                ('question_body', models.TextField(help_text='Тело вопроса (сам текст)')),
                ('question_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('solved', 'Solved')], default='open', help_text='Статус вопроса', max_length=20)),
                ('question_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания вопроса')),
                ('question_updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения вопроса')),
                ('user', models.ForeignKey(help_text='Автор вопроса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор решения', primary_key=True, serialize=False)),
                ('solution_body', models.TextField(help_text='Тело решения (сам текст)')),
                ('solution_is_best', models.BooleanField(default=False, help_text='Является ли решение лучшим')),
                ('solution_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания решения')),
                ('solution_updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения решения')),
                ('question', models.ForeignKey(help_text='Вопрос к которому представлено решение', on_delete=django.db.models.deletion.CASCADE, to='qa.question')),
                ('user', models.ForeignKey(help_text='Автор решения', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solutions',
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='unique_solution_user_pair')],
            },
        ),
    ]
