# Generated by Django 6.0.3 on 2026-03-30 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionEdits',
            fields=[
                ('solution_edit_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор изменения', primary_key=True, serialize=False)),
                ('solution_edit_body_before', models.TextField(help_text='Текст решения до правок')),
                ('solution_edit_body_after', models.TextField(help_text='Новый текст решения')),
                ('solution_edit_is_approved', models.BooleanField(default=False, help_text='Была ли одобрена правка')),
                ('solution_edit_edited_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время правки')),
                ('solution', models.ForeignKey(help_text='Решение к которому относится изменение', on_delete=django.db.models.deletion.CASCADE, to='qa.solution')),
                ('user', models.ForeignKey(help_text='Автор изменений', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solution_edits',
            },
        ),
    ]
