# Generated by Django 6.0.3 on 2026-04-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='Автор комментария', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(help_text='Автор вопроса', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(help_text='Вопрос к которому представлено решение', on_delete=django.db.models.deletion.CASCADE, to='qa.question'),
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(help_text='Автор решения', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solutionedits',
            name='solution',
            field=models.ForeignKey(help_text='Решение к которому относится изменение', on_delete=django.db.models.deletion.CASCADE, to='qa.solution'),
        ),
        migrations.AddField(
            model_name='solutionedits',
            name='user',
            field=models.ForeignKey(help_text='Автор изменений', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(help_text='Тип контента (вопрос или решение)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, поставивший голос', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id'], name='comments_content_cd20f6_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='comments_parent__9f8798_idx'),
        ),
        migrations.AddConstraint(
            model_name='solution',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_solution_user_pair'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['content_type', 'object_id'], name='votes_content_a606f3_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='votes_user_id_72a822_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_vote_user_target'),
        ),
    ]
