# Generated by Django 6.0.3 on 2026-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_alter_solutionedits_solution_edit_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionedits',
            name='solution_edit_is_approved',
            field=models.BooleanField(blank=True, default=False, help_text='Была ли одобрена правка', null=True),
        ),
    ]
