# Generated by Django 6.0.3 on 2026-03-31 16:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_alter_solutionedits_solution_edit_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionedits',
            name='solution_edit_is_approved',
            field=models.BooleanField(blank=True, help_text='Была ли одобрена правка', null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор комментария', primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('question', 'Question'), ('solution', 'Solution')], help_text='Тип цели комментария (вопрос или решение)', max_length=20)),
                ('target_id', models.UUIDField(help_text='ID вопроса или решения, к которому оставлен комментарий')),
                ('body', models.TextField(help_text='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания комментария')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительский комментарий (для вложенных комментариев)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='qa.comment')),
                ('user', models.ForeignKey(help_text='Автор комментария', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comments',
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='comments_target__71256e_idx'), models.Index(fields=['parent'], name='comments_parent__9f8798_idx')],
            },
        ),
    ]
