# Generated by Django 6.0.3 on 2026-03-31 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_migrate_to_genericforeignkey'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_target__71256e_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='target_type',
        ),
    ]
