# Generated by Django 6.0.3 on 2026-04-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_remove_comment_comments_target__71256e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Родительский комментарий (для вложенных комментариев)', null=True, on_delete=django.db.models.deletion.CASCADE, to='qa.comment'),
        ),
    ]
