# Generated by Django 6.0.3 on 2026-04-01 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qa', '0008_alter_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор голоса', primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID объекта, к которому поставлен голос')),
                ('vote_type', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], help_text='Тип голоса (upvote или downvote)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания голоса')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата изменения голоса')),
                ('content_type', models.ForeignKey(help_text='Тип контента (вопрос или решение)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='Пользователь, поставивший голос', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votes',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='votes_content_a606f3_idx'), models.Index(fields=['user'], name='votes_user_id_72a822_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_vote_user_target')],
            },
        ),
    ]
