# Generated by Django 6.0.3 on 2026-03-26 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор достижения', primary_key=True, serialize=False)),
                ('achievement_code', models.CharField(help_text='Машиночитаемый идентификатор достижения', max_length=128, unique=True)),
                ('achievement_name', models.CharField(help_text='Название достижения', max_length=128)),
                ('achievement_description', models.TextField(help_text='Описание достижения')),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор пользователя', primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='Никнейм пользователя', max_length=64, unique=True)),
                ('user_email', models.EmailField(help_text='Почта пользователя', max_length=255, unique=True)),
                ('user_role', models.CharField(choices=[('user', 'User'), ('expert', 'Expert'), ('admin', 'Admin')], default='user', help_text='Роль пользователя', max_length=15)),
                ('user_reputation_score', models.PositiveIntegerField(default=0, help_text='Репутация пользователя')),
                ('user_avatar_url', models.ImageField(blank=True, help_text='Аватар пользователя', upload_to='')),
                ('user_bio', models.TextField(blank=True, help_text='Дополнительная информация о пользователе')),
                ('user_is_blocked', models.BooleanField(default=False, help_text='Отображает, заблокирован ли пользователь')),
                ('user_created_at', models.DateTimeField(auto_now_add=True, help_text='Дата регистрации пользователя')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ReputationTransaction',
            fields=[
                ('reputation_transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор транзакции', primary_key=True, serialize=False)),
                ('reputation_transaction_amount', models.IntegerField(help_text='Количество снятой/добавленной репутации')),
                ('reputation_transaction_reason', models.CharField(choices=[('best_solution', 'Best solution'), ('solution_upvoted', 'Solution upvoted'), ('solution_downvoted', 'Solution downvoted'), ('question_upvoted', 'Question upvoted'), ('achievement_earned', 'Achievement earned'), ('admin_adjustment', 'Admin adjustment')], help_text='Причина начисления/снятия репутации', max_length=128)),
                ('user', models.ForeignKey(help_text='Пользователь транзакции', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reputation_transactions',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('user_achievement_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор записи', primary_key=True, serialize=False)),
                ('user_achievement_earned_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время получения достижения')),
                ('achievement', models.ForeignKey(help_text='Уникальный идентификатор достижения', on_delete=django.db.models.deletion.CASCADE, to='user.achievement')),
                ('user', models.ForeignKey(help_text='Уникальный идентификатор пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement')],
            },
        ),
    ]
