# Generated by Django 6.0.3 on 2026-03-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_avatar_url',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_bio',
            field=models.TextField(blank=True, help_text='Дополнительная информация о пользователе', null=True),
        ),
    ]
