# Generated by Django 6.0.3 on 2026-03-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_user_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_is_blocked',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активирована ли учётная запись пользователя'),
        ),
    ]
